spring:
  profiles:
    active: dev #环境
  application:
    name: elasticBg-client
  devtools:
    restart:
      poll-interval: 5000ms
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/ui/
    favicon:
       enabled: false
  main:
    allow-bean-definition-overriding: true






