spring:
  profiles:
    active: dev #环境
  mvc: #jsp 支持
    view:
      suffix: .jsp
      prefix: /WEB-INF/ui/
  devtools:
    restart:
      poll-interval: 5000ms

mybatis: #mybatis
  mapper-locations: mapper/*.xml
  config-location: classpath:mybatis_cfg.xml
  type-aliases-package: com.faceghost.elasticbg.base.model

mapper: #通用mapper
  identity: MYSQL
  mappers: com.faceghost.elasticbg.util.BaseMapper

elasticbg:
  email_host_name: smtp.qq.com  #设置邮件服务器
  email_use_ssl: true #设置是否使用安全连接
  email_ssl_port: 456 #设置安全连接端口号
  email_charset: UTF-8 #发送Email编码
  email_user_name: xx@xx.com #发送Email用户名
  email_user_pwd: xx #发送Email密码


